using Client.GridAction;
using System;
using System.Windows.Controls;

namespace Client.D_Views
{
    /// <summary>
    /// Logique d'interaction pour QueryView.xaml
    /// </summary>
    public partial class QueryView : UserControl
    {
        public QueryView()
        {
           InitializeComponent();
        }
        private void gridContainingRequeteResults_AutoGeneratedColumns(object sender, EventArgs e)
        {
            AutoGeneratedColumnAction AutoGeneratedColumnAction = new AutoGeneratedColumnAction();
            AutoGeneratedColumnAction.call(gridContainingRequeteResults);
        }
    }
}
