using Client.D_ViewModels;
using System;
using System.Windows.Controls;

namespace Client.D_Views
{
    /// <summary>
    /// Logique d'interaction pour QueryView.xaml
    /// </summary>
    public partial class QueryView : UserControl
    {
        public QueryView()
        {
           InitializeComponent();
        }
        private void gridContainingRequeteResults_AutoGeneratedColumns(object sender, EventArgs e)
        {
            QueryViewModel qvm = this.DataContext as QueryViewModel;
            qvm.AutoGeneratedColumns(gridContainingRequeteResults);
            qvm.ExecuteRefeshRequested += Qvm_ExecuteRefeshRequested;
        }

        private void Qvm_ExecuteRefeshRequested(DataGrid obj)
        {
            QueryViewModel qvm = this.DataContext as QueryViewModel;
            for (int i = 0; i < gridContainingRequeteResults.Columns.Count; ++i)
            {
               qvm.colHeader[gridContainingRequeteResults.Columns[i].SortMemberPath] = (string)gridContainingRequeteResults.Columns[i].Header;
            }
        }
    }
}
